<?php
$pageTitle='أبشر للتوريدات والمعدات | توريدات صناعية وكتالوج ذكي';
require 'includes/header.php';
$pub=array_values(array_filter(array_reverse(products()),fn($p)=>($p['status']??'')==='published'));
$brandNames=['BOSCH','Makita','HILTI','DEWALT','Milwaukee','STANLEY','metabo','LINCOLN ELECTRIC'];
$catIcons=['⚙','⌁','▣','⚒','◫','⌬','◈','⬡'];
$industries=[
 ['الورش والتصنيع','لحام • قطع • تجليخ • معدات ورش','welding'],
 ['الصيانة والتشغيل MRO','عدد • مواتير • طلمبات • قطع غيار','maintenance'],
 ['السلامة المهنية','مهمات حماية • أحذية • خوذ • ملابس','safety'],
 ['خدمة السيارات','معدات رفع • هواء • تشخيص • صيانة','automotive'],
 ['المقاولات والمواقع','معدات كهربائية • قياس • تخزين • مناولة','construction'],
 ['الهواء والسوائل','كمبروسورات • نيوماتيك • طلمبات • خراطيم','pumps']
];
?>
<section class="hero-store">
  <div class="hero-copy">
    <span class="eyebrow">توريدات صناعية منظمة للمحترفين</span>
    <h1>كل ما يحتاجه<br><span>المصنع والورشة</span></h1>
    <p>ابحث بالمنتج أو الموديل أو رقم القطعة، تصفح حسب النشاط أو العلامة التجارية، واطلب عرض سعر موحد لقائمة مشتريات شركتك.</p>
    <div class="hero-actions"><a class="primary-cta" href="catalog.php">تصفح الكتالوج <b>←</b></a><a class="ghost-cta" href="quote.php">▤ طلب عرض سعر</a></div>
    <div class="quick-lanes">
      <a class="quick-lane" href="catalog.php?q=عدد+كهربائية"><span><strong>العدد الكهربائية</strong><small>شنيور • هيلتي • صواريخ • بطاريات</small></span><b>←</b></a>
      <a class="quick-lane" href="catalog.php?q=لحام"><span><strong>اللحام والقطع</strong><small>ماكينات • أسلاك • مستهلكات</small></span><b>←</b></a>
      <a class="quick-lane" href="catalog.php?q=مناولة"><span><strong>المناولة والرفع</strong><small>أوناش • روافع • معدات حركة</small></span><b>←</b></a>
      <a class="quick-lane" href="catalog.php?q=سلامة"><span><strong>السلامة المهنية</strong><small>حماية شخصية ومهمات مواقع</small></span><b>←</b></a>
    </div>
  </div>
  <div class="hero-visual"><img src="assets/hero-industrial.svg" alt="معدات صناعية احترافية"><div class="hero-shade"></div><div class="hero-tech"><span>INDUSTRIAL SUPPLY</span><strong>اختيار أسرع<br>توريد أوضح</strong><i></i><small>MODEL • PART NO. • BRAND • CATEGORY</small></div></div>
</section>
<section class="brand-strip"><div class="brand-strip-head"><strong>أشهر العلامات التجارية</strong><a href="brands.php">عرض الكل ←</a></div><div class="brand-strip-row"><?php foreach($brandNames as $b):?><a href="catalog.php?q=<?=urlencode($b)?>"><?=e($b)?></a><?php endforeach;?></div></section>
<section class="section compact"><div class="section-title"><div><span class="eyebrow">الأقسام الرئيسية</span><h2>هيكل واضح للوصول للمعدة بسرعة</h2></div><a href="catalog.php">عرض جميع الأقسام ←</a></div><div class="department-grid"><?php foreach(array_slice(categories(),0,7) as $i=>$c):?><a class="department" href="catalog.php?category=<?=urlencode($c['name'])?>"><span class="dept-icon"><?=e($catIcons[$i]??'⚙')?></span><div><h3><?=e($c['name'])?></h3><p><?=e(implode(' • ',array_slice($c['children']??[],0,2)))?></p></div><b>←</b></a><?php endforeach;?><a class="department all-depts" href="catalog.php"><span class="dept-icon">▦</span><div><h3>جميع الأقسام</h3><p>استعرض الكتالوج الكامل</p></div><b>←</b></a></div></section>
<section class="section compact" id="industries"><div class="section-title"><div><span class="eyebrow">تصفح حسب النشاط</span><h2>حلول أقرب لطريقة عمل الشركات والمصانع</h2></div></div><div class="industry-grid"><?php foreach($industries as $i=>$x):?><article class="industry-card <?=$i===2?'alert':''?>"><span class="tag">INDUSTRY COLLECTION</span><h3><?=e($x[0])?></h3><p><?=e($x[1])?></p><a href="catalog.php?q=<?=urlencode($x[2])?>">استعرض المنتجات ←</a></article><?php endforeach;?></div></section>
<section class="section compact products-section"><div class="section-title"><div><span class="eyebrow">منتجات مميزة</span><h2>معدات جاهزة للاستعلام</h2></div><a href="catalog.php">عرض جميع المنتجات ←</a></div><div class="product-grid premium-products"><?php foreach(array_slice($pub,0,6) as $i=>$p):?><a class="product-card premium <?=$i===0?'offer-card':''?>" href="product.php?slug=<?=urlencode($p['slug'])?>"><?php if($i===0):?><span class="offer-flag">عرض مميز</span><?php endif;?><div class="product-image"><?php if(!empty($p['image'])):?><img src="<?=e($p['image'])?>" alt="<?=e($p['name'])?>"><?php else:?><div class="product-placeholder"><span><?=e(u_first($p['brand']??'A'))?></span><small><?=e($p['brand']??'INDUSTRIAL')?></small></div><?php endif;?></div><div class="product-body"><small><?=e($p['brand']??'')?> · <?=e($p['category']??'')?></small><h3><?=e($p['name'])?></h3><p><?=e($p['short_description']??'معدات صناعية احترافية متاحة للاستعلام وطلب عرض السعر.')?></p><div class="card-foot"><strong><?=!empty($p['price'])?money($p['price']):e($p['price_label']??'اطلب السعر')?></strong><span>التفاصيل ←</span></div></div></a><?php endforeach;?><?php if(!$pub):?><?php foreach([['Bosch GBH 2-26 DRE','Bosch','مثقاب وتكسير احترافي'],['Hilti TE 70-ATC/AVR','Hilti','شاكوش تكسير SDS Max'],['Makita GA9020','Makita','صاروخ قطع وتجليخ'],['DEWALT DCD796','DeWalt','دريل شحن 18 فولت'],['Stanley STHT0-74101','Stanley','طقم عدة يدوية'],['Metabo W 850-125','Metabo','صاروخ قطع 125 مم']] as $i=>$x):?><a class="product-card premium <?=$i===0?'offer-card':''?>" href="catalog.php?q=<?=urlencode($x[0])?>"><?php if($i===0):?><span class="offer-flag">عرض مميز</span><?php endif;?><div class="product-image"><div class="product-placeholder"><span><?=e($x[1][0])?></span><small><?=e($x[1])?></small></div></div><div class="product-body"><small><?=e($x[1])?> · معدات صناعية</small><h3><?=e($x[0])?></h3><p><?=e($x[2])?></p><div class="card-foot"><strong>اطلب السعر</strong><span>التفاصيل ←</span></div></div></a><?php endforeach;?><?php endif;?></div></section>
<section class="section compact"><div class="section-title"><div><span class="eyebrow">مكتب المشتريات</span><h2>للشركات والمشروعات والقوائم الكبيرة</h2></div></div><div class="procure-grid"><div class="procure-card"><span class="eyebrow">PROCUREMENT DESK</span><h3>أرسل قائمة الموديلات أو أرقام القطع</h3><p>نرتب المنتجات، نراجع البدائل، ونحوّلها إلى طلب عرض سعر واحد بدل البحث اليدوي عن كل صنف.</p><div class="procure-points"><span>بحث بالموديل ورقم القطعة</span><span>مطابقة العلامة التجارية</span><span>اقتراح بدائل عند الحاجة</span><span>تجميع الطلب في RFQ واحد</span></div><div class="status-line"><i class="status-dot"></i> خدمة مخصصة لطلبات B2B</div></div><div class="procure-card"><span class="eyebrow">SOURCE CONTROL</span><h3>مواصفات أوضح قبل الشراء</h3><p>كل منتج يمكن ربطه بمصدر ومراجعة فنية قبل النشر، مع إبراز المنتجات والعروض التي تحتاج قرارًا سريعًا.</p><div class="status-line"><i class="status-dot"></i> بيانات موثقة ومراجعة</div><div class="status-line alert-line"><i class="status-dot"></i> العروض والتنبيهات المهمة فقط بالقرمزي</div></div></div></section>
<section class="section compact"><div class="b2b-panel"><div class="b2b-copy"><span class="eyebrow">B2B / PROJECT SOURCING</span><h2>حلول توريد للمشروعات والشركات</h2><p>أرسل قائمة الاحتياجات وسنرتبها داخل عرض سعر واحد مع الموديلات والبدائل المتاحة.</p><div class="b2b-actions"><a class="primary-cta" href="quote.php">ابدأ طلب توريد</a><a class="ghost-cta" href="services.php">خدمات الشركات</a></div></div><div class="b2b-metrics"><div><span>01</span><b>استلام قائمة الاحتياجات</b></div><div><span>02</span><b>مطابقة الموديلات</b></div><div><span>03</span><b>مراجعة البدائل</b></div><div><span>04</span><b>إصدار عرض السعر</b></div></div></div></section>
<?php require 'includes/footer.php';?>
