<?php
$pageTitle='أبشر للتوريدات والمعدات | توريدات صناعية وكتالوج ذكي';
require 'includes/header.php';
$pub=array_values(array_filter(array_reverse(products()),fn($p)=>($p['status']??'')==='published'));
$brandNames=['BOSCH','Makita','HILTI','DEWALT','Milwaukee','STANLEY','metabo','LINCOLN ELECTRIC'];
$catIcons=['⚙','⌁','▣','⚒','◫','⌬','◈','⬡'];
?>
<section class="hero-store">
  <div class="hero-copy">
    <span class="eyebrow">شريكك الموثوق في عالم التوريدات الصناعية</span>
    <h1>كل ما يحتاجه<br><span>المصنع والورشة</span></h1>
    <p>معدات صناعية، عدد، تجهيزات ورش ومهمات سلامة من علامات تجارية موثوقة، مع بحث ذكي بالموديل وطلب عرض سعر مباشر للشركات.</p>
    <div class="hero-actions"><a class="primary-cta" href="catalog.php">تصفح المنتجات <b>←</b></a><a class="ghost-cta" href="quote.php">▤ طلب عرض سعر</a></div>
    <div class="hero-services"><div><i>⌘</i><span><b>دعم فني متخصص</b><small>قبل وبعد البيع</small></span></div><div><i>▣</i><span><b>منتجات موثقة</b><small>مصادر ومواصفات واضحة</small></span></div><div><i>⌁</i><span><b>توريد للشركات</b><small>طلبات ومشروعات B2B</small></span></div></div>
  </div>
  <div class="hero-visual"><img src="assets/hero-industrial.svg" alt="معدات صناعية احترافية"><div class="hero-shade"></div><div class="hero-tech"><span>INDUSTRIAL GRADE</span><strong>الأداء<br>يصنع الفرق</strong><i></i><small>ENGINEERED FOR PROFESSIONALS</small></div></div>
</section>
<section class="brand-strip"><div class="brand-strip-head"><strong>أشهر العلامات التجارية</strong><a href="brands.php">عرض الكل ←</a></div><div class="brand-strip-row"><?php foreach($brandNames as $b):?><a href="catalog.php?q=<?=urlencode($b)?>"><?=e($b)?></a><?php endforeach;?></div></section>
<section class="section compact"><div class="section-title"><div><span class="eyebrow">الأقسام الرئيسية</span><h2>كل احتياجات موقع العمل</h2></div><a href="catalog.php">عرض جميع الأقسام ←</a></div><div class="department-grid"><?php foreach(array_slice(categories(),0,7) as $i=>$c):?><a class="department" href="catalog.php?category=<?=urlencode($c['name'])?>"><span class="dept-icon"><?=e($catIcons[$i]??'⚙')?></span><div><h3><?=e($c['name'])?></h3><p><?=e(implode(' • ',array_slice($c['children']??[],0,2)))?></p></div><b>←</b></a><?php endforeach;?><a class="department all-depts" href="catalog.php"><span class="dept-icon">▦</span><div><h3>جميع الأقسام</h3><p>استعرض الكتالوج الكامل</p></div><b>←</b></a></div></section>
<section class="section compact products-section"><div class="section-title"><div><span class="eyebrow">منتجات مميزة</span><h2>معدات جاهزة للاستعلام</h2></div><a href="catalog.php">عرض جميع المنتجات ←</a></div><div class="product-grid premium-products"><?php foreach(array_slice($pub,0,6) as $p):?><a class="product-card premium" href="product.php?slug=<?=urlencode($p['slug'])?>"><div class="product-image"><?php if(!empty($p['image'])):?><img src="<?=e($p['image'])?>" alt="<?=e($p['name'])?>"><?php else:?><div class="product-placeholder"><span><?=e(u_first($p['brand']??'A'))?></span><small><?=e($p['brand']??'INDUSTRIAL')?></small></div><?php endif;?></div><div class="product-body"><small><?=e($p['brand']??'')?> · <?=e($p['category']??'')?></small><h3><?=e($p['name'])?></h3><p><?=e($p['short_description']??'معدات صناعية احترافية متاحة للاستعلام وطلب عرض السعر.')?></p><div class="card-foot"><strong><?=!empty($p['price'])?money($p['price']):e($p['price_label']??'اطلب السعر')?></strong><span>التفاصيل ←</span></div></div></a><?php endforeach;?><?php if(!$pub):?><?php foreach([['Bosch GBH 2-26 DRE','Bosch','مثقاب وتكسير احترافي'],['Hilti TE 70-ATC/AVR','Hilti','شاكوش تكسير SDS Max'],['Makita GA9020','Makita','صاروخ قطع وتجليخ'],['DEWALT DCD796','DeWalt','دريل شحن 18 فولت'],['Stanley STHT0-74101','Stanley','طقم عدة يدوية'],['Metabo W 850-125','Metabo','صاروخ قطع 125 مم']] as $x):?><a class="product-card premium" href="catalog.php?q=<?=urlencode($x[0])?>"><div class="product-image"><div class="product-placeholder"><span><?=e($x[1][0])?></span><small><?=e($x[1])?></small></div></div><div class="product-body"><small><?=e($x[1])?> · معدات صناعية</small><h3><?=e($x[0])?></h3><p><?=e($x[2])?></p><div class="card-foot"><strong>اطلب السعر</strong><span>التفاصيل ←</span></div></div></a><?php endforeach;?><?php endif;?></div></section>
<section class="section compact"><div class="b2b-panel"><div class="b2b-copy"><span class="eyebrow">B2B / PROJECT SOURCING</span><h2>حلول توريد للمشروعات والشركات</h2><p>أرسل قائمة الموديلات والكميات، وسنرتب طلبك داخل عرض سعر واحد مع البدائل المتاحة ومصادر المواصفات.</p><div class="b2b-actions"><a class="primary-cta" href="quote.php">ابدأ طلب توريد</a><a class="ghost-cta" href="services.php">خدمات الشركات</a></div></div><div class="b2b-metrics"><div><span>01</span><b>استلام قائمة الاحتياجات</b></div><div><span>02</span><b>مطابقة الموديلات</b></div><div><span>03</span><b>مراجعة البدائل</b></div><div><span>04</span><b>إصدار عرض السعر</b></div></div></div></section>
<?php require 'includes/footer.php';?>
